In [1]:
import numpy as np

In [2]:
data = np.random.randn(2, 3)

In [5]:
data

array([[-0.72390378,  1.2545816 ,  0.43492728],
       [ 0.85833478, -1.43762453,  0.14014118]])

In [6]:
my_arr = np.arange(1000000)

In [7]:
my_list = list(range(1000000))

In [8]:
%time for _ in range(10): my_arr2 = my_arr * 2

Wall time: 21 ms


In [9]:
%time for _ in range(10): my_list2 = [ x * 2 for x in my_list]

Wall time: 946 ms


In [10]:
data * 10

array([[ -7.23903782,  12.54581597,   4.3492728 ],
       [  8.58334777, -14.37624528,   1.40141185]])

In [11]:
data + data

array([[-1.44780756,  2.50916319,  0.86985456],
       [ 1.71666955, -2.87524906,  0.28028237]])

In [12]:
data.shape

(2, 3)

In [13]:
data.dtype

dtype('float64')

In [14]:
data1 = [6,7.5,8,0,1]

In [15]:
arr1 = np.array(data1)

In [16]:
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [17]:
#Nested sequences
data2 = [[1,2,3,4],[5,6,7,8]]

In [18]:
arr2 = np.array(data2)

In [19]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [23]:
arr2.shape

(2, 4)

In [24]:
arr2.ndim

2

In [25]:
arr2.dtype

dtype('int32')

In [26]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [27]:
np.zeros((3,6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [28]:
np.empty((2,3,2))

array([[[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]]])

In [29]:
arr1 = np.array([1,2,3], dtype=np.int64)

In [30]:
arr1

array([1, 2, 3], dtype=int64)

In [31]:
arr = np.array([3.7,-1.2,2.6,0.5,12.9,10.1])

In [32]:
arr

array([  3.7,  -1.2,   2.6,   0.5,  12.9,  10.1])

In [33]:
arr.astype(np.int32)

array([ 3, -1,  2,  0, 12, 10])

In [34]:
arr.dtype

dtype('float64')

In [35]:
arr

array([  3.7,  -1.2,   2.6,   0.5,  12.9,  10.1])

In [36]:
numeric_strings = np.array(['1.25','-9.6','42'], dtype = np.string_)

In [37]:
numeric_strings

array([b'1.25', b'-9.6', b'42'], 
      dtype='|S4')

In [38]:
numeric_strings.astype(float)

array([  1.25,  -9.6 ,  42.  ])

In [40]:
arr = np.array([[1,2,3],[4,5,6]])

In [41]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
arr * arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [43]:
arr - arr

array([[0, 0, 0],
       [0, 0, 0]])

In [44]:
1 / arr

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.25      ,  0.2       ,  0.16666667]])

In [45]:
arr ** 2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [46]:
arr2 = np.array([[0.,4.,1.],[7.,2.,12.]])

In [47]:
arr2

array([[  0.,   4.,   1.],
       [  7.,   2.,  12.]])

In [48]:
arr2 > arr 

array([[False,  True, False],
       [ True, False,  True]], dtype=bool)

In [49]:
arr = np.arange(10)

In [50]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
arr[5]

5

In [52]:
arr[5:8]

array([5, 6, 7])

In [53]:
arr[5:8] =12

In [54]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [55]:
arr_slice = arr[5:8]

In [56]:
arr_slice

array([12, 12, 12])

In [57]:
arr_slice[1] = 1234

In [58]:
arr

array([   0,    1,    2,    3,    4,   12, 1234,   12,    8,    9])

In [59]:
arr_slice

array([  12, 1234,   12])

In [60]:
arr_slice[:]

array([  12, 1234,   12])

In [61]:
arr_slice[:] = 64

In [62]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [63]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [64]:
arr2d[2]

array([7, 8, 9])

In [65]:
arr2d[0][2]

3

In [66]:
arr2d[0,2]

3

In [67]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [68]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [69]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [70]:
arr3d.shape

(2, 2, 3)

In [71]:
arr3d[0]=42

In [72]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [76]:
arr3d[0] = arr2d[0:2]

In [77]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])